scenario: scenarios.limo_delivery

agent:
  namespaces: "/limo" 
  behavior_tree_xml: "default_bt.xml"

bt_runner:
  bt_tick_rate: 10.0 
  bt_visualiser:
    enabled: True
    screen_width: 600 
    screen_height: 600 
  profiling_mode: False
