scenario: scenarios.nav_scenario

agent:
  namespace: ""
  behavior_tree_xml: "default_bt.xml"

bt_runner:
  bt_tick_rate: 10.0

  bt_visualiser:
    enabled: True
    screen_width: 850
    screen_height: 850

  profiling_mode: False
